[application]

# App (Project) Name
name = "{{project-name}}"

# current support: web, desktop
# default: web
default_platform = "desktop"

out_dir = "dist"

asset_dir = "public"

[web.app]

# HTML title tag content
title = "Rusty Messenger"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = false

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["reset.css", "style.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []